In [2]:
from sklearn.preprocessing import PolynomialFeatures
#from preprocessing.polynomial_features import PolynomialFeatures
import numpy as np
X = np.arange(6)
print(X.reshape(-1,1))
poly = PolynomialFeatures(2)

(poly.transform(X))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


NotFittedError: This PolynomialFeatures instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [33]:
from itertools import chain
from itertools import combinations_with_replacement as combinations_w_r
max_degree = 2
X = np.arange(2)

print(X)
n_features = X.shape[0]
print(n_features)
comb = combinations_w_r
start = 1
iter = chain.from_iterable(
    comb(range(n_features), i) for i in range(start, max_degree + 1)
)
if True:
    iter = chain(comb(range(n_features), 0), iter)
for i in iter:
    print(i)
l=[]




[0 1]
2
()
(0,)
(1,)
(0, 0)
(0, 1)
(1, 1)


In [31]:
print(iter)
for i in iter:
    out=1
    print(i)
    for j in i:
        out*=X[:,j]
    print(out,'**')
    l.append(out)

In [5]:
from sklearn.datasets import make_regression
import matplotlib.pyplot as plt
import numpy as np
x, y = make_regression(n_samples = 100, n_features = 1,
                       n_informative = 1, noise = 10, random_state = 42)
  

  
# Adding x0=1 column to x array.
X_New = np.array([np.ones(len(x)), x.flatten()])
X_New

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1. 

In [6]:
import jax
import jaxl

ModuleNotFoundError: No module named 'jaxl'

In [7]:
import jax
import pandas as pd
x, y = make_regression(n_samples = 5, n_features = 1,
                       n_informative = 1, noise = 0, random_state = 42)

print(type(x))
N = 5
P = 3
X = pd.DataFrame(np.random.randn(N, P))
y = pd.Series(np.random.randn(N))
theta = np.ones((P+1, 1),dtype = float)
print(theta)
#X_fit = np.array([np.ones(len(X)), X.flatten()]).transpose()
X_fit = X.copy(deep=True)
X_fit.insert(loc = 0, column = -1 , value = np.ones(X.shape[0]))
X_fit=X_fit.to_numpy()
y=y.to_numpy()
print(X_fit.shape,theta.shape,y.shape)
mse_grad = 2*np.mean(X_fit.T @ (X_fit @ (theta) - y),axis=1)
def f(theta, X_fit, y ):
    #return ((y - (X_fit @ theta))**2).mean()
    return np.mean((y - (X_fit @ theta)).T @ (y - (X_fit @ theta)))
mse_grad1 = jax.grad(f,argnums=0)(theta,X_fit,y)
for i in mse_grad1:
    print(i)
mse_grad.reshape(4,1)
mse_grad

<class 'numpy.ndarray'>
[[1.]
 [1.]
 [1.]
 [1.]]
(5, 4) (4, 1) (5,)
[13.248629]
[2.5007424]
[10.753599]
[12.281649]


array([13.24863019,  2.50074284, 10.75359912, 12.28164862])

In [18]:
a=np.array([1]) @ np.array([1])

TypeError: argument of type 'type' is not iterable

In [115]:

x = np.array([i*np.pi/180 for i in range(60,300,4)])
print(x.shape)
xt=np.transpose(x)
print(xt.shape)

(60,)
(60,)


In [16]:
l=[[1,2,3],[4,5,6]]
k = np.array(l)
k*4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [17]:
# -*- coding: utf-8 -*-
"""Q2_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-h6mR7sy_h7Yi1dKE4xCb8nKprgkVDj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from linearRegression.linear_regression import LinearRegression
from sklearn.metrics import mean_squared_error as mse

np.random.seed(45)

N = 90
P = 10
X = pd.DataFrame(np.random.randn(N, P))
y = pd.Series(np.random.randn(N))

import time

    

LR = LinearRegression(fit_intercept=True)

# Call Gradient Descent here
print("Gradient Type: Manual")
time1 = time.time()
for i in range(10):
    LR.fit_gradient_descent(X, y, batch_size=0, gradient_type='manual', penalty_type = 'unregularized', num_iters=10, lr=0.01)
time2 = time.time()
y_hat = LR.predict(X)
print("--Unregularized rmse: ", np.sqrt(mse(y,y_hat)))
print("time taken: ", (time2-time1/10))

time1 = time.time()
for i in range(10):
    LR.fit_gradient_descent(X, y, batch_size=0, gradient_type='manual', penalty_type = 'l2', num_iters=10, lr=0.01)
time2 = time.time()
y_hat = LR.predict(X)
print("--L2 rmse: ", np.sqrt(mse(y,y_hat)))
print("time taken: ", (time2-time1/10))

print("---------------------------")

print("Gradient Type: JAX")
time1 = time.time()
for i in range(10):
    LR.fit_gradient_descent(X, y, batch_size=0, gradient_type='jax', penalty_type = 'unregularized', num_iters=10, lr=0.01)
time2 = time.time()
y_hat = LR.predict(X)
print("--Unregularized rmse: ", np.sqrt(mse(y,y_hat)))
print("time taken: ", (time2-time1/10))

time1 = time.time()
for i in range(10):
    LR.fit_gradient_descent(X, y, batch_size=0, gradient_type='jax', penalty_type = 'l1', num_iters=10, lr=0.01)
time2 = time.time()
y_hat = LR.predict(X)
print("--L1 rmse: ", np.sqrt(mse(y,y_hat)))
print("time taken: ", (time2-time1/10))

time1 = time.time()
for i in range(10): 
    LR.fit_gradient_descent(X, y, batch_size=0, gradient_type='jax', penalty_type = 'l2', num_iters=10, lr=0.01)
time2 = time.time()
y_hat = LR.predict(X)
print("--L2 rmse: ", np.sqrt(mse(y,y_hat)))
print("time taken: ", (time2-time1/10))
print("---------------------------")

print("Running SGD with ridge regularization")
time1 = time.time()
for i in range(10):
    LR.fit_gradient_descent(X, y, batch_size=1, gradient_type='manual', penalty_type = 'l2', num_iters=10, lr=0.01)
time2 = time.time()
y_hat = LR.predict(X)
print("--rmse: ", np.sqrt(mse(y,y_hat)))
print("time taken: ", (time2-time1/10))
print("---------------------------")

print("Running mini-batch SGD with ridge regularization")
time1 = time.time()
for i in range(10):
    LR.fit_gradient_descent(X, y, batch_size=10, gradient_type='manual', penalty_type = 'l2', num_iters=10, lr=0.01)
time2 = time.time()
y_hat = LR.predict(X)
print("--rmse: ", np.sqrt(mse(y,y_hat)))
print("time taken: ", (time2-time1/10))


print("Running SGD with momentum and ridge regularization")
time1 = time.time()
for i in range(10):
    LR.fit_SGD_with_momentum(X, y, gradient_type='manual', penalty_type = 'l2', num_iters=10, lr=0.01, beta=0.9)
time2 = time.time()
y_hat = LR.predict(X)
print("--rmse: ", np.sqrt(mse(y,y_hat)))
print("time taken: ", (time2-time1/10))




ModuleNotFoundError: No module named 'linearRegression'