In [5]:

import sys
sys.path.append('/home/saikrishna/Documents/ML_Assignment4/assignment-4-sujeet-saikrishna/')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from linearRegression.linear_regression import LinearRegression
from sklearn.datasets import make_regression
from metrics import *
from preprocessing.polynomial_features import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
import time
import os
from os import path
import seaborn as sns

np.random.seed(45)

In [8]:
def time_plot(timeData):
    df = pd.DataFrame(data=timeData)
    heatmap = pd.pivot_table(df, values='norm', index=['n_samples'], columns='degree')
    sns.heatmap(heatmap, cmap="flare")

    plt.savefig('./Plots/Question5/varying.png')
    plt.clf()


In [11]:
norm_theta = {'n_samples':[], 'degree':[], 'norm':[]}
for n_samples in range(1000,5500,1000):
    #X, y = make_regression(n_samples=100, n_features=2, noise=20, random_state=45)
    X = np.array([i*np.pi/180 for i in range(60+n_samples,300+n_samples,2)])
    y = 3*X + 8 + np.random.normal(0,3,len(X))
    X=X.reshape(-1,1)
    # X = np.random.rand(n_samples, 1)
    # y = X.squeeze()**2 + 0.1*np.random.randn(n_samples)
    norm = []
    for degree in [1,3,5,7,9]:
        print('n_samples: ',n_samples,' degree: ',degree)
        poly = PolynomialFeatures(degree=degree,include_bias=True)
        X_train = np.array([])
        for i in range(len(X)):
            if X_train.shape[0] != 0:
                X_train = np.vstack((X_train,poly.transform(X[i])))
            else:
                X_train = poly.transform(X[i])
        X_train = StandardScaler().fit_transform(X_train)
        LR = LinearRegression(fit_intercept=True)
        theta = LR.fit_sklearn_LR(X_train,y)
        norm_theta['n_samples'].append(n_samples)
        norm_theta['degree'].append(degree)
        norm_theta['norm'].append(np.linalg.norm(theta))
for i in range(len(norm_theta['norm'])):
    norm_theta['norm'][i] = (norm_theta['norm'][i]-min(norm_theta['norm']))/(max(norm_theta['norm'])-min(norm_theta['norm']))

n_samples:  1000  degree:  1
n_samples:  1000  degree:  3
n_samples:  1000  degree:  5
n_samples:  1000  degree:  7
n_samples:  1000  degree:  9
n_samples:  2000  degree:  1
n_samples:  2000  degree:  3
n_samples:  2000  degree:  5
n_samples:  2000  degree:  7
n_samples:  2000  degree:  9
n_samples:  3000  degree:  1
n_samples:  3000  degree:  3
n_samples:  3000  degree:  5
n_samples:  3000  degree:  7
n_samples:  3000  degree:  9
n_samples:  4000  degree:  1
n_samples:  4000  degree:  3
n_samples:  4000  degree:  5
n_samples:  4000  degree:  7
n_samples:  4000  degree:  9
n_samples:  5000  degree:  1
n_samples:  5000  degree:  3
n_samples:  5000  degree:  5
n_samples:  5000  degree:  7
n_samples:  5000  degree:  9


In [12]:

if not path.exists('Plots/Question5/'):
    os.makedirs('Plots/Question5/')
time_plot(norm_theta)

<Figure size 640x480 with 0 Axes>

In [14]:
x=[[1,2,3],[4,5,6]]
x=np.array(x)
y=[[1,2,3]]
y=np.array(y)
x=StandardScaler().fit_transform(x)
print(x)
y=(y-np.mean(y))/np.sqrt(np.var(y))
y

[[-1. -1. -1.]
 [ 1.  1.  1.]]


array([[-1.22474487,  0.        ,  1.22474487]])